### ISSUE TITLE
Doctor Class Instruction Error

### ISSUE THREAD

**Issue by torianne02** [learn-co-curriculum/ruby-objects-has-many-through-lab#16]
"The Doctor class needs a class method .all that lists each **artist** in the class variable."

Small error, but this should say, "The Doctor class needs a class method .all that lists each **doctor** in the class variable."

**Comment by drakeltheryuujin** [comment]
Yes, thank you for your feed back @torianne02   .

The text has been updated to accurately reflect the expectations of the lab (in each case).
💙
