### ISSUE TITLE
Does the Artist need a Doctor?

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/ruby-objects-has-many-through-lab#17]
I think there is a little mixup here:

"The Doctor class needs a class method .all that lists each artist in the class variable."

Thanks,

Valerie

**Comment by drakeltheryuujin** [comment]
Yes, thank you for your feed back @ValerieHMoore  .

The text has been updated to accurately reflect the expectations of the lab (in each case).
💙
