### ISSUE TITLE
There's a problem with the test for the #new_appointment method in the Doctor class.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ruby-objects-has-many-through-lab#21]
Hello. Regarding the Doctor class's #new_appointment method, both the README and the #describe block in the test for #new_appointment seem to indicate that #new_appointment needs to accept its arguments in the following order: date, patient.

The only problem is, that order of arguments is supposed to be the other way around, or the test will fail. I have attached a screenshot to add some clarity.

Thanks for looking into this!

Regards,

Sdcrouse 

![has many objects through lab screenshot](https://user-images.githubusercontent.com/38870640/45259817-a03cd480-b38a-11e8-9cbf-a73f1dda2569.gif)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sdcrouse.

We have updated the readme to reflect the tests and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by cyantis** [comment]
Hello! Looks like this is still out of order. The instructions read: "An Appointment should be initialized with a date (as a string, like "Monday, August 1st"), a patient, and a doctor." But I had to order it (patient, doctor, date) to get the tests to pass.

Thanks!

**Comment by Sdcrouse** [comment]
I think you have to reopen it as a new issue.

**Comment by cyantis** [comment]
Thanks for the tip! Will do...

**Comment by Sdcrouse** [comment]
Also, I think it would help to reference this issue in a hyperlink.

**Comment by maxwellbenton** [comment]
Hi @cyantis and @Sdcrouse,

@cyantis, thank you for bringing this issue up. I was able to look at your cohort's repository and noticed that it hadn't received the most recent content updates. This lesson should now have the most recent commits, including this fix. It won't fix your fork, but should be fixed for any other students that haven't forked this lesson yet.

Thank you both for contributing!

**Comment by cyantis** [comment]
Fabulous, thanks!

**Comment by Sdcrouse** [comment]
Excellent! Thanks for clearing that up.
