### ISSUE TITLE
Some of the tests are missing.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ruby-objects-has-many-through-lab#22]
Hello. First of all, I understand if some of these tests may not be needed, in order to avoid redundancy.

That having been said, the README says that the Genre class needs a Genre.all method and a #new_song method. It also says that the Patient class needs a Patient.all method, a #name method, and an #appointments method. Unfortunately, there are no tests to check for this, despite other classes having similar tests for similar methods. To be fair, though, one of the tests for the Patient class does in fact require that the #appointments method be defined, in order to pass.

I know that these are minor issues, but thank you for looking into this.

Regards,

Sdcrouse

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sdcrouse.

We have updated the readme, added tests in the patient and genre specs and your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
