### ISSUE TITLE
Missing end keyword in 06_patient_spec

### ISSUE THREAD

**Issue by cassaram09** [learn-co-curriculum/ruby-objects-has-many-through-lab#23]
`06_patient_spec.rb` needs an `end` keyword to close the `describe` block. A syntax error is thrown if the student tries to run the test suite. 

```
describe '#appointments' do
    it 'has many doctors through appointments' do
      doctor_dog = Doctor.new('Dog')
      doctor_howser = Doctor.new('Howser')
      steve = Patient.new('Steve from Blues Clues')
      appointment_one = steve.new_appointment(doctor_dog, 'Friday, January 32nd')
      appointment_two = steve.new_appointment(doctor_howser, 'Saturday, January 32nd')

      expect(steve.appointments).to include(appointment_one)
      expect(steve.appointments).to include(appointment_two)
    end
#add end keyword here
```

**Comment by drakeltheryuujin** [comment]
Hi @cassaram09 

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
