### ISSUE TITLE
Error in 06_patient_spec.rb

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/ruby-objects-has-many-through-lab#27]
Need an 'end' on line 42 of master branch copy. 

  describe '#appointments' do
    it 'has many doctors through appointments' do
      doctor_dog = Doctor.new('Dog')
      doctor_howser = Doctor.new('Howser')
      steve = Patient.new('Steve from Blues Clues')
      appointment_one = steve.new_appointment(doctor_dog, 'Friday, January 32nd')
      appointment_two = steve.new_appointment(doctor_howser, 'Saturday, January 32nd')

      expect(steve.appointments).to include(appointment_one)
      expect(steve.appointments).to include(appointment_two)
    end
#end here

**Comment by drakeltheryuujin** [comment]
Hi @justinddaniel,

The master and solution branches have the following code:
```
  describe '#appointments' do
    it 'has many doctors through appointments' do
      doctor_dog = Doctor.new('Dog')
      doctor_howser = Doctor.new('Howser')
      steve = Patient.new('Steve from Blues Clues')
      appointment_one = steve.new_appointment(doctor_dog, 'Friday, January 32nd')
      appointment_two = steve.new_appointment(doctor_howser, 'Saturday, January 32nd')

      expect(steve.appointments).to include(appointment_one)
      expect(steve.appointments).to include(appointment_two)
    end
  end
```
There does not appear to be any syntax errors. 
If you do not believe that this issue has been addressed, please re-open this issue. 💙
