### ISSUE TITLE
Bug when using binding.pry in this location

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/ruby-objects-has-many-through-lab#28]
Whenever using `binding.pry` in the position show in the Genre class/artists method below, you end up having to exit the local IDE and losing whatever work isn't saved (to my knowledge). 

```
require 'pry'

class Genre
  attr_accessor :name

  @@all = []

  def initialize(genre_name)
    @name = genre_name
    @@all << self
  end

  def self.all
    @@all
  end

  def songs
    Song.all.select do |song|
      song.genre == self
    end
  end

  def artists
    binding.pry
    # Song.all.select do |artist|
    #   artist.artist ==
    # end
  end



end
```

After iterating through the various instances you get: 

![screen shot 2018-10-18 at 5 54 48 am](https://user-images.githubusercontent.com/24820716/47150119-34a82a00-d29b-11e8-8a7f-b86df5064a2f.png)

You can't press `enter` or `return` to get back to the normal terminal. 

![screen shot 2018-10-18 at 5 56 13 am](https://user-images.githubusercontent.com/24820716/47150142-48539080-d29b-11e8-8b51-1ccbcf9cc298.png)

![screen shot 2018-10-18 at 5 56 23 am](https://user-images.githubusercontent.com/24820716/47150144-4be71780-d29b-11e8-99ed-e379c061e8a0.png)

Here is the code for the other classes that I had:

```
require 'pry'

class Artist
  attr_accessor :name

  @@all = []

  def initialize(name)
    @name = name
    @@all << self
  end

  def self.all
    @@all
  end

  def new_song(song_name, genre)
    Song.new(song_name, self, genre)
  end

  def songs

    Song.all.select do |song|
      song.artist == self
    end
  end

  def genres
    # binding.pry
    songs.collect do |song|
      song.genre
    end
  end


end
```
```
require 'pry'

class Song
  attr_accessor :name, :artist, :genre

  @@all = []

  def initialize(song_name, artist, genre)
    @name = song_name
    @artist = artist
    @genre = genre
    @@all << self
  end

  def self.all
    @@all
  end

  # def genre
  #   binding.pry
  # end


end
```

**Comment by drakeltheryuujin** [comment]
Hi @aburk3,

This request sounds like an issue with the Learn IDE. Raising issues on GitHub should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.). If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
