### ISSUE TITLE
Error in Artist #genres test

### ISSUE THREAD

**Issue by bethurban** [learn-co-curriculum/ruby-objects-has-many-through-lab#36]
The test for #genres under Artist expects `jay_z.songs.first.genre` to equal `rap` - the test should call `jay_z.songs.last.genre`, however, to access the most recent genre, which was created inside the #genres test.

Calling `jay_z.songs.first.genre` calls the genre created in earlier Artist tests, meaning the instances don't match up and the #genres test fails.

**Comment by maxwellbenton** [comment]
Hi @bethurban,

Thank you for spotting this and providing feedback. We've updated the tests for this lab and incorporated this fix into the updates to prevent this issue from occuring  for ftuure students.

We apologize for any inconvenience this may have caused, but thank you for contributing to a Learn lesson!
