### ISSUE TITLE
Doctor add appointments test message errors

### ISSUE THREAD

**Issue by coltonstaab1** [learn-co-curriculum/ruby-objects-has-many-through-lab#5]
Hi there, the Doctor add_appointments test is very confusing--it references adding appointments to the artists appointments array. I'd take a second look at it? Error message attached.

![dr add_appointment test](https://cloud.githubusercontent.com/assets/16259851/12222966/e301aab6-b77f-11e5-9369-9dba1f69f6af.jpg)

**Comment by AnnJohn** [comment]
Hi @coltonstaab1 thanks for raising this issue and sorry about the confusion. We'e updated the specs so that it adds the appointment  correctly to the doctor's appointments array. 

Thanks!
