### ISSUE TITLE
Incorrect test description

### ISSUE THREAD

**Issue by shmulim** [learn-co-curriculum/ruby-objects-has-many-through-lab#6]
Doctor
  #patients
    has many patients, through patients

should be:

Doctor
  #patients
    has many patients, through appointments

**Comment by AnnJohn** [comment]
hi @shmulim could you let us know where specifically in the tests this occurs? A screenshot and/or line numbers would be really helpful. Thanks!

**Comment by shmulim** [comment]
<img width="1066" alt="screen shot 2016-01-13 at 5 17 08 pm" src="https://cloud.githubusercontent.com/assets/6036212/12313113/9bdb1982-ba19-11e5-952a-0dfcc19658b6.png">

Line 42.

**Comment by AnnJohn** [comment]
thanks! we updated the specs.
