### ISSUE TITLE
This must be an error ("it "has many patients, through patients")

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/ruby-objects-has-many-through-lab#8]
Line 42, in doctor_spec.rb

it "has many patients, through patients" do

**Comment by AnnJohn** [comment]
might not be an error @ruchiramani, but can you take a look and respond? thanks

**Comment by ruchiramani** [comment]
It is not an error, its describing the relation between patients and appointments.In this case the appointment belongs to a patient.
