### ISSUE TITLE
Is this (also) an error? ("Appointment #doctor belongs to a doctor")?

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/ruby-objects-has-many-through-lab#9]
Line 23  in "appointment_spec.rb"

"Appointment #doctor belongs to a doctor"

**Comment by AnnJohn** [comment]
might not be an error @ruchiramani, but can you take a look and respond? thanks

**Comment by ruchiramani** [comment]
It is not an error, its describing the relation between doctors and appointments.In this case the appointment belongs to a doctor.
